Adds support for swipe actions
3sidedcube/iOS-ThunderTable pull request #27
Opened 2018-02-15 12:55 UTC by simonmitchell

Adds support for swipe actions via `RowActionable`,`SwipeActionsConfigurable` and `Row/Section` protocols

2018-02-20 09:12 UTC, ryanbourneuk approved these changes

2018-02-20 09:12 UTC, ryanbourneuk commented on ThunderTable/TableRow+Actions.swift
> +/// call the completionHandler (iOS 11 and above) to reset the context to its normal state (e.g. when swiping, resets to unswiped state)
If this is a separate sentence to the one above, could it start with a capital please? Got a bit confused as I thought it was one sentence to begin with :)

2018-02-20 09:12 UTC, ryanbourneuk commented on ThunderTable/TableSection.swift
> +	var rowLeadingSwipeActionsConfiguration: SwipeActionsConfigurable? { get }
Indentation seems a bit off here, guessing Github has got confused with tabs and spaces again? :)

2018-02-21 10:53 UTC, MattCheetham requested changes

2018-02-21 10:53 UTC, MattCheetham commented on ThunderTable/TableRow+Actions.swift
> +		rowAction.backgroundEffect =  backgroundEffect
Double space after the `=` ?

2018-02-22 16:26 UTC, simonmitchell commented
@MattCheetham @ryanbourneuk changes made

2018-03-01 09:42 UTC, MattCheetham approved these changes

2018-03-01 09:47 UTC, merged