Adds InputPickerRow capability back in to framework
3sidedcube/iOS-ThunderTable pull request #28
Opened 2018-02-15 16:03 UTC by simonmitchell

2018-02-20 09:17 UTC, ryanbourneuk commented on ThunderTable/InputPickerViewCell.swift
> +	open override func awakeFromNib() {
Indentation seems a bit off in this file.

2018-02-20 09:21 UTC, ryanbourneuk commented on ThunderTable/Extensions.swift
> +		set {
If there's nothing within the `set` here, does it need to have an empty block? I can't remember if they're required or not :)

2018-02-21 10:55 UTC, MattCheetham commented on ThunderTable/Extensions.swift
> +		set {
Yeah if you don't add the set {} it doesn't get recognised. Strange Swift limitation.

2018-02-21 10:59 UTC, MattCheetham requested changes

2018-02-21 10:59 UTC, MattCheetham commented on ThunderTable/Extensions.swift
> +		set {
Should be on one line though

2018-02-21 10:59 UTC, MattCheetham commented on ThunderTable/InputPickerRow.swift
> +		super.configure(cell: cell, at: indexPath, in: tableViewController)
Would you not want to call super before the guard? Seems strange to just return without calling super if the cell isn't our subclass type.

2018-02-21 10:59 UTC, MattCheetham commented on ThunderTable/InputPickerViewCell.swift
> +open class InputPickerViewCell: TableViewCell {
Documentation?

2018-02-22 16:31 UTC, simonmitchell commented
@MattCheetham @ryanbourneuk done :)

2018-03-01 09:43 UTC, MattCheetham approved these changes

2018-03-01 16:56 UTC, merged